### ISSUE TITLE
Nothing is displayed

### ISSUE THREAD

**Issue by elogent** [skylight-software/impulse#16]
Running `bower install` gives an error:

    $ bower install
    bower MODULE_NOT_FOUND      Cannot find module 'form-data'

And when the project is served using `gulp serve`, nothing is displayed in my browser. I am using Firefox 40.0.3 on Ubuntu 15.04.

**Comment by miller9904** [comment]
This should be named something like 'install error'.

**Comment by elogent** [comment]
It turns out I wasn't installing everything correctly. Here are the steps to properly install and run Impulse (as of the time of this writing):

    $ npm install -g gulp bower form-data
    $ git clone https://github.com/skylight-software/impulse.git
    $ cd impulse
    $ git checkout release-0.1
    $ npm install
    $ bower install
    $ gulp serve
