### ISSUE TITLE
Data Privacy

### ISSUE THREAD

**Issue by miller9904** [skylight-software/impulse#3]
THE reason that people will use Impulse is that it's a private assistant.  Period.  That's why we need to define a solid base for how we're going to protect user privacy.  Here's my ideas:

##### 1. Run the machine learning algorithms on device
As long as there is a way to serialize the data so that different system implementations of the machine learning algorithms can read and process it, this should work well.

##### 2. Keep data in the user's physical control
Instead of syncing data through the cloud, let's sync data over a WiFi connection.  Each database of user data would operate separately from each other until two devices were connected to the same WiFi network.  Then they would connect in a peer to peer fashion and exchange diffs or something.  We'll have to figure out how to manage different versions of the same database.

##### 3. Fine grain privacy controls
We will sometimes need to send user data to other services (e.g. the weather API needs location information.)  We need to make sure that the user knows exactly what data we will be giving out, and we should also give a link to the service's privacy policy.  And, give the user an option to permanently allow an individual permission.

**Comment by redrobohood** [comment]
So, just to clarify, user databases would be stored per-device, and then databases on different devices owned by the same user would be able to synchronize when connected to the same wi-fi network?

For managing versions of user databases, the best options I can think of are:

- Use Git (or Mercurial, etc.) 
- Find a DVCS designed specifically for databases

**Comment by miller9904** [comment]
Yes, that's how databases would work.  Whatever we use, it needs to be able to combine all the things that the different clients learn into one database they they can all use without the user even noticing.

**Comment by redrobohood** [comment]
Will the program only add data to the databases, or will it also change/remove data over time? If the latter, what kinds of data will it need to change/remove?

**Comment by miller9904** [comment]
Databases will hold many things, such as machine learning models, locations, account data, auth tokens, and anything else we need to save.  Yes, data will change and can be removed.

**Comment by redrobohood** [comment]
OK. In that case, we're going to need to finalize the database model before we can start figuring out how to sync databases.

**Comment by miller9904** [comment]
Sounds good.
