### ISSUE TITLE
Color scheme

### ISSUE THREAD

**Issue by miller9904** [skylight-software/impulse#4]
Here are some color schemes I have thrown together.  Tell me which one you like the best.  To generate color schemes, please use the [Material Palette](http://www.materialpalette.com/).

* [Green & Yellow](http://www.materialpalette.com/green/yellow)
* [Teal & Orange] (http://www.materialpalette.com/teal/orange)
* [Pink & Amber] (http://www.materialpalette.com/pink/amber)
* [Deep Purple & Yellow](http://www.materialpalette.com/deep-purple/yellow)
* [Deep Purple & Pink](http://www.materialpalette.com/deep-purple/pink)

**Comment by redrobohood** [comment]
I rather like the [Purple & Deep Purple](http://www.materialpalette.com/purple/deep-purple) palette for this project, but that's probably just my synesthesia.

**Comment by miller9904** [comment]
Yeah, that's a really strange color combination.  Do you like any of mine?

**Comment by redrobohood** [comment]
I like the [Deep Purple & Yellow](http://www.materialpalette.com/deep-purple/yellow) and [Deep Purple & Pink](http://www.materialpalette.com/deep-purple/pink) ones, I suppose.

**Comment by miller9904** [comment]
OK, let's go with [Deep Purple & Yellow](http://www.materialpalette.com/deep-purple/yellow) for now.  Reopen the issue if we need to change.
