### ISSUE TITLE
Database Schema

### ISSUE THREAD

**Issue by miller9904** [skylight-software/impulse#6]
Here is my proposed schema for the databases used by Impulse.

### Database 1: Timeline
*This table is where the cards proposed to be shown will go, ordered by time.*

* **id** - Unique record number
* **module** - The module that issued the card.  (e.g. 'Weather' or 'News')
* **type** - The class of card.  Either an Alert or a Recommendation.  Use the `Impulse.cards.type` constants.
* **class** - The class of card, such as 'News' or 'Weather'.  Use `Impulse.cards.moduleDefinedCardClasses` constants.
* **data** - The data used to render the card, such as the title, actions, etc.
* **validStart** - The starting time the card becomes valid.
* **validEnd** - The time the card expires.

### Database 2: Algorithm Stores
*This table stores the models used by the machine learning algorithms.*

* **id** - Model id.
* **governing** - what type of card the model governs.
* **data** - Model data.

### Database 3: Events
*This is where we store card events, such as interactions and dismisses.*

* **id** - Event id.
* **timestamp** - The time the event occurred.
* **type** - The class of event, such as Action or Dismissed.  Use `Impulse.cards.events` constants.
* **class** - The class of card that the event was issued by.
* **module** - The module that issued the card.
* **card-id** - The record id of the card itself.

### Database 4: User Data

I really don't know how we should set up this database, and it may be best to wait until we know how  the data is returned by the services to decide.

**Comment by elogent** [comment]
Impressive. So, how will these different tables change over time? Obviously data insertion could be allowed in most cases, but what will cause existing tuples to be changed?

For deletion of tuples, will there be a simple expiration system that causes old tuples to be deleted after a certain (perhaps variable) amount of time, or will there be other ways of deletion as well?

**Comment by miller9904** [comment]
Yes, old entries in the timeline will be deleted after a time.  Events are needed for the machine learning models, so I don't know if we will delete old entries or not.

**Comment by miller9904** [comment]
Though, come to think of it, we might only want to train on recent data.  So perhaps old events would be deleted, too.  That's a question best left until we implement the ml algorithms.

**Comment by elogent** [comment]
OK, so under what circumstances (and in what tables) will existing tuples be allowed to change?

**Comment by miller9904** [comment]
Once a record is written, I don't see any cause to modify it.  What were you thinking of?

**Comment by elogent** [comment]
Nothing; I agree that there isn't a reason to modify existing data. This schema definitely seems like a solid starting point.
